package com.xworkz.order.runner;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;

import com.xworkz.order.dto.ProductDTO;
import com.xworkz.product.order.ProductAscCompany;
import com.xworkz.product.order.ProductAscId;
import com.xworkz.product.order.ProductAscName;
import com.xworkz.product.order.ProductAscPrice;
import com.xworkz.product.order.ProductAscQuality;
import com.xworkz.product.order.ProductAscQuantity;
import com.xworkz.product.order.ProductDescCompany;
import com.xworkz.product.order.ProductDescId;
import com.xworkz.product.order.ProductDescName;
import com.xworkz.product.order.ProductDescPrice;
import com.xworkz.product.order.ProductDescQuality;
import com.xworkz.product.order.ProductDescQuantity;


public class ProductRunner {

	public static void main(String[] args) {

		// id,name,company,quantity,price,quality;
		ProductDTO productDTO = new ProductDTO(1, "Colgate", "Colgate-Palmolive", 50d, 30d, 3f);
		ProductDTO productDTO1 = new ProductDTO(2, "Hair Color", "indigo", 100d, 50d, 5f);
		ProductDTO productDTO2 = new ProductDTO(3, "hand Wash", "Lifebuoy", 500d, 678d, 4f);
		ProductDTO productDTO3 = new ProductDTO(4, "Lasi", "Amul", 250d, 50d, 3.5f);
		ProductDTO productDTO4 = new ProductDTO(5, "curad", "Amul", 500d, 25d, 4f);
		ProductDTO productDTO5 = new ProductDTO(6, "Ice dream", "Amul", 150d, 45d, 4.3f);
		ProductDTO productDTO6 = new ProductDTO(7, "Butter", "Amul", 100d, 129d, 3.9f);
		ProductDTO productDTO7 = new ProductDTO(8, "Buttermilk", "Amul", 500d, 35d, 3.7f);
		ProductDTO productDTO8 = new ProductDTO(9, "Cheese", "Amul", 50d, 29d, 3.6f);
		ProductDTO productDTO9 = new ProductDTO(10, "Biscuits", "Parle", 70d, 5d, 4.8f);
		ProductDTO productDTO10 = new ProductDTO(11, "KarckJack", "Parle", 20d, 15d, 3.1f);
		ProductDTO productDTO11 = new ProductDTO(12, "Manaco", "Parle", 50d, 20d, 4.0f);
		ProductDTO productDTO12 = new ProductDTO(13, "Kiss Me Chocalet", "Parle", 5d, 1d, 5f);
		ProductDTO productDTO13 = new ProductDTO(14, " Ketchup", "Kissan", 500d, 150d, 3.8f);
		ProductDTO productDTO14 = new ProductDTO(15, "Jams", "Kissan", 500d, 270d, 4.2f);
		ProductDTO productDTO15 = new ProductDTO(16, "MTR Masala", "Kissan", 100d, 25d, 4.0f);
		ProductDTO productDTO16 = new ProductDTO(17, "solt", "Patanjali", 500d, 30d, 3.3f);
		ProductDTO productDTO17 = new ProductDTO(18, "Atta", "Patanjali", 500d, 120d, 4.1f);
		ProductDTO productDTO18 = new ProductDTO(19, "Biscuits", "Patanjali", 100d, 28d, 3.1f);
		ProductDTO productDTO19 = new ProductDTO(20, "Ghee", "Patanjali", 500d, 310d, 4.8f);
		ProductDTO productDTO20 = new ProductDTO(21, "Rice", "Patanjali", 2d, 96d, 4.1f);
		ProductDTO productDTO21 = new ProductDTO(22, "Allovira", "Patanjali", 100d, 125d, 3.9f);
		ProductDTO productDTO22 = new ProductDTO(23, "Good Day", "Britannia", 150d, 36d, 4.0f);
		ProductDTO productDTO23 = new ProductDTO(24, "Crackers", "Britannia", 50d, 10d, 3.4f);
		ProductDTO productDTO24 = new ProductDTO(25, "Milk Bikis", "Britannia", 500d, 35d, 3.2f);
		ProductDTO productDTO25 = new ProductDTO(26, "Jim Jam", "Britannia", 130d, 170d, 3.0f);
		ProductDTO productDTO26 = new ProductDTO(27, "Little Hearts", "Britannia", 150d, 10d, 4.7f);
		ProductDTO productDTO27 = new ProductDTO(28, "Honey", "Dabur", 250d, 150d, 3.8f);
		ProductDTO productDTO28 = new ProductDTO(29, "Masalas", "Everest", 100d, 45d, 4.2f);
		ProductDTO productDTO29 = new ProductDTO(30, "oil", "Fortune", 500d, 90d, 3.9f);
		ProductDTO productDTO30 = new ProductDTO(31, "Atta", "Fortune", 250d, 40d, 4.3f);
		ProductDTO productDTO31 = new ProductDTO(32, "Rice", "Fortune", 1d, 75d, 3.5f);
		ProductDTO productDTO32 = new ProductDTO(33, "Rice", "Daawat", 1.5d, 150d, 5f);
		ProductDTO productDTO33 = new ProductDTO(34, "Rice", "Surya", 1d, 50d, 2.8f);
		ProductDTO productDTO34 = new ProductDTO(35, "Rice", "Basmati", 500d, 22d, 3.9f);
		ProductDTO productDTO35 = new ProductDTO(36, "Gold Rice", "star", 2d, 120d, 2.9f);
		ProductDTO productDTO36 = new ProductDTO(37, "Oil", "Star", 1d, 175d, 3.8f);
		ProductDTO productDTO37 = new ProductDTO(38, " Chips", "Star", 100d, 5d, 3.4f);
		ProductDTO productDTO38 = new ProductDTO(39, "Rice", "Star", 500d, 34d, 4.1f);
		ProductDTO productDTO39 = new ProductDTO(40, "Sugar", "Star", 1d, 36d, 3.5f);
		ProductDTO productDTO40 = new ProductDTO(41, "Water", "Star", 1d, 20d, 4.2f);
		ProductDTO productDTO41 = new ProductDTO(42, "RMD", "Rmd", 10d, 19d, 4.3f);
		ProductDTO productDTO42 = new ProductDTO(43, "Nandini milk", "KPTML", 200d, 15d, 4.9f);
		ProductDTO productDTO43 = new ProductDTO(44, "Atta", "Ashirwad", 500d, 90d, 4.2f);
		ProductDTO productDTO44 = new ProductDTO(45, "Horlicks", "Unilever", 500d, 150d, 3.8f);
		ProductDTO productDTO45 = new ProductDTO(46, "soap", "Lux", 100d, 28d, 4.1f);
		ProductDTO productDTO46 = new ProductDTO(47, "Soap", "Lifebuoy", 50d, 15d, 4.5f);
		ProductDTO productDTO47 = new ProductDTO(48, "Soap", "Dettol", 100d, 50d, 4.4f);
		ProductDTO productDTO48 = new ProductDTO(49, "Toothpaste", "Close Up", 100d, 25d, 3.7f);
		ProductDTO productDTO49 = new ProductDTO(50, "Toothpaste", "Pepsodent", 150d, 35d, 4.0f);
		ProductDTO productDTO50 = new ProductDTO(51, "Shampoo", "Clinic plus", 10d, 3d, 3.9f);
		ProductDTO productDTO51 = new ProductDTO(52, "Ponds", "skin  cream", 100d, 20d, 4.1f);
		ProductDTO productDTO52 = new ProductDTO(53, "skin  cream", "Fair & lovely", 20d, 15d, 3.5f);
		ProductDTO productDTO53 = new ProductDTO(54, "agarbathi", "cycle", 100d, 20d, 4.3f);
		ProductDTO productDTO54 = new ProductDTO(55, "sweets", "Jamuna", 250d, 120d, 4.1f);
		ProductDTO productDTO55 = new ProductDTO(56, "Leep Care", "Nivea", 50d, 139d, 4.5f);
		ProductDTO productDTO56 = new ProductDTO(57, "Face Wash", "Garnier", 100d, 80d, 3.9f);
		ProductDTO productDTO57 = new ProductDTO(58, "Face Wash", "Cetaphil", 250d, 30d, 3f);
		ProductDTO productDTO58 = new ProductDTO(59, "sweets", "Anand", 10d, 75d, 4.7f);
		ProductDTO productDTO59 = new ProductDTO(60, "Cycle", "Herculars", 10d, 35d, 4.1f);
		ProductDTO productDTO60 = new ProductDTO(61, "Papad", "Rambandu", 250d, 55d, 3.6f);
		ProductDTO productDTO61 = new ProductDTO(62, "Bisleri", "Bisleri", 1d, 20d, 5f);
		ProductDTO productDTO62 = new ProductDTO(63, "Face Wash", "himalayan", 100d, 290d, 3.7f);
		ProductDTO productDTO63 = new ProductDTO(64, "Hair Color", "Garnier", 10d, 30d, 4.4f);
		ProductDTO productDTO64 = new ProductDTO(65, "Hair Color", "herbal", 150d, 130d, 4.2f);
		ProductDTO productDTO65 = new ProductDTO(66, "Hair Color", "gray", 80d, 220d, 3.4f);
		ProductDTO productDTO66 = new ProductDTO(67, "face mask", "Garnier", 90d, 110d, 3.2f);
		ProductDTO productDTO67 = new ProductDTO(68, "Rose Water", "pooja", 100d, 90d, 4f);
		ProductDTO productDTO68 = new ProductDTO(69, "Rose Water", "dabur", 250d, 25d, 4.5f);
		ProductDTO productDTO69 = new ProductDTO(70, "Soft drink", "Pepsi", 500d, 95d, 4.6f);
		ProductDTO productDTO70 = new ProductDTO(71, "Soft drink", "Sprite ", 750d, 90d, 3.9f);
		ProductDTO productDTO71 = new ProductDTO(72, "Soft drink", "Coca-Cola", 550d, 69d, 4f);
		ProductDTO productDTO72 = new ProductDTO(73, "Soft drink", "Mountain Dew", 150d, 15d, 3.9f);
		ProductDTO productDTO73 = new ProductDTO(74, "Soft drink", "Fanta", 100d, 20d, 3.8f);
		ProductDTO productDTO74 = new ProductDTO(75, "Soft drink", "Cola", 500d, 110d, 4f);
		ProductDTO productDTO75 = new ProductDTO(76, "Soft drink", "Root Beer", 250d, 50d, 2.9f);
		ProductDTO productDTO76 = new ProductDTO(77, "Soft drink", "Red Bull", 450d, 80d, 4.7f);
		ProductDTO productDTO77 = new ProductDTO(78, "Soft drink", "Mirinda", 1.5d, 125d, 3.4f);
		ProductDTO productDTO78 = new ProductDTO(151, "Soft drink", "Sai Ghee", 1d, 270d, 4.5f);
		ProductDTO productDTO79 = new ProductDTO(79, "Soft drink", "Ginger Ale", 100d, 18d, 3.7f);
		ProductDTO productDTO80 = new ProductDTO(80, "Soft drink", "Thums Up", 500d, 45d, 4.7f);
		ProductDTO productDTO81 = new ProductDTO(81, "Soft drink", "Lemonade", 150d, 33d, 4.1f);
		ProductDTO productDTO82 = new ProductDTO(82, "Soft drink", "Fresca", 200d, 30d, 2.9f);
		ProductDTO productDTO83 = new ProductDTO(83, "Soft drink", "Limca", 250d, 18d, 3.5f);
		ProductDTO productDTO84 = new ProductDTO(84, "Soft drink", "Diet Pepsi", 50d, 25d, 4f);
		ProductDTO productDTO85 = new ProductDTO(85, "Soft drink", "Carbonated Drink", 250d, 32d, 3f);
		ProductDTO productDTO86 = new ProductDTO(86, "Soft drink", "Sunkist", 350d, 50d, 3.7f);
		ProductDTO productDTO87 = new ProductDTO(87, "Soft drink", "Surge", 200d, 30d, 4f);
		ProductDTO productDTO88 = new ProductDTO(88, "Soft drink", "Sierra Mist", 100d, 50d, 2.6f);
		ProductDTO productDTO89 = new ProductDTO(89, "Soft drink", "Mello Yello", 150d, 40d, 3.0f);
		ProductDTO productDTO90 = new ProductDTO(90, "Soft drink", "Schweppes", 300d, 80d, 4.2f);
		ProductDTO productDTO91 = new ProductDTO(91, "Soft drink", "Diet Coke", 5d, 190d, 3.3f);
		ProductDTO productDTO92 = new ProductDTO(92, "Soft drink", "Dr Pepper", 500d, 400d, 4f);
		ProductDTO productDTO93 = new ProductDTO(93, "Chocolate", "kit kat", 100d, 10d, 5f);
		ProductDTO productDTO94 = new ProductDTO(94, "Chocolate", "Snickers", 50d, 30d, 3f);
		ProductDTO productDTO95 = new ProductDTO(95, "Chocolate", "Toblerone", 50d, 30d, 3f);
		ProductDTO productDTO96 = new ProductDTO(96, "Chocolate", "White Chocolate", 50d, 30d, 3f);
		ProductDTO productDTO97 = new ProductDTO(97, "Chocolate", "Mars", 50d, 30d, 3f);
		ProductDTO productDTO98 = new ProductDTO(98, "Chocolate", "Cadbury", 50d, 30d, 3f);
		ProductDTO productDTO99 = new ProductDTO(99, "Chocolate", "Galaxy", 50d, 30d, 3f);
		ProductDTO productDTO100 = new ProductDTO(100, "Chocolate", "Twix", 50d, 30d, 3f);
		ProductDTO productDTO101 = new ProductDTO(101, "Chocolate", "Munch", 50d, 30d, 3f);
		ProductDTO productDTO102 = new ProductDTO(102, "Chocolate", "Godiva", 50d, 30d, 3f);
		ProductDTO productDTO103 = new ProductDTO(103, "Chocolate", "Ruby Chocalet", 50d, 30d, 3f);
		ProductDTO productDTO104 = new ProductDTO(104, "Chocolate", "Dove", 50d, 30d, 3f);
		ProductDTO productDTO105 = new ProductDTO(105, "Chocolate", "Nestle", 50d, 30d, 3f);
		ProductDTO productDTO106 = new ProductDTO(106, "Chocolate", "Lindt", 50d, 30d, 3f);
		ProductDTO productDTO107 = new ProductDTO(107, "Chocolate", "Milkybar", 50d, 30d, 3f);
		ProductDTO productDTO108 = new ProductDTO(108, "Chocolate", "Gemas", 50d, 30d, 3f);
		ProductDTO productDTO109 = new ProductDTO(109, "Chocolate", "Bournville", 50d, 30d, 3f);
		ProductDTO productDTO110 = new ProductDTO(110, "Chocolate", "3 Musketters", 50d, 30d, 3f);
		ProductDTO productDTO111 = new ProductDTO(111, "Perfume", "Wild Stone", 250d, 220d, 4f);
		ProductDTO productDTO112 = new ProductDTO(112, "Perfume", "Fogg", 150d, 160d, 3f);
		ProductDTO productDTO113 = new ProductDTO(113, "Perfume", "Axe", 180d, 250d, 3.6f);
		ProductDTO productDTO114 = new ProductDTO(114, "Perfume", "Nautica", 50d, 30d, 3f);
		ProductDTO productDTO115 = new ProductDTO(115, "Perfume", "Nivea", 50d, 30d, 3f);
		ProductDTO productDTO116 = new ProductDTO(116, "Perfume", "Park Avenue", 100d, 199d, 3.9f);
		ProductDTO productDTO117 = new ProductDTO(117, "Perfume", "Kam Sutar", 50d, 30d, 3f);
		ProductDTO productDTO118 = new ProductDTO(118, "Perfume", "God Father", 100d, 899d, 5f);
		ProductDTO productDTO119 = new ProductDTO(119, "Perfume", "Mini Spray", 50d, 30d, 3f);
		ProductDTO productDTO120 = new ProductDTO(120, "Perfume", "Yardley", 100d, 424.90d, 3.6f);
		ProductDTO productDTO121 = new ProductDTO(121, "Perfume", "Paco Rabanne", 500d, 4950d, 5f);
		ProductDTO productDTO122 = new ProductDTO(122, "Perfume", "Calvin", 250d, 3449d, 4f);
		ProductDTO productDTO123 = new ProductDTO(123, "Perfume", "Beardo", 50d, 30d, 3f);
		ProductDTO productDTO124 = new ProductDTO(124, "Perfume", "ustraa Base", 100d, 799d, 3.8f);
		ProductDTO productDTO125 = new ProductDTO(125, "Oil", "Olive", 250d, 130d, 3.3f);
		ProductDTO productDTO126 = new ProductDTO(126, "Oil", "Canola ", 500d, 90d, 3.5f);
		ProductDTO productDTO127 = new ProductDTO(127, "Oil", "Cocount", 1d, 210d, 4f);
		ProductDTO productDTO128 = new ProductDTO(128, "Oil", "peanut", 250d, 80d, 3.7f);
		ProductDTO productDTO129 = new ProductDTO(129, "Oil", "SunFlower", 750d, 120d, 4.1f);
		ProductDTO productDTO130 = new ProductDTO(130, "Oil", "Almond", 1.5d, 200d, 4.8f);
		ProductDTO productDTO131 = new ProductDTO(131, "Oil", "Hemp", 500d, 220d, 3.3f);
		ProductDTO productDTO132 = new ProductDTO(132, "Palm Oil", "Palm", 100d, 170d, 3.8f);
		ProductDTO productDTO133 = new ProductDTO(133, "Pine nut Oil", "Pine", 500d, 136d, 2.9f);
		ProductDTO productDTO134 = new ProductDTO(134, "Cottonseed Oil", "PMS", 750d, 450d, 4.9f);
		ProductDTO productDTO135 = new ProductDTO(135, "Chips", "Bingo", 150d, 20d, 3.6f);
		ProductDTO productDTO136 = new ProductDTO(136, "Chips", "Lays", 100d, 10d, 3.7f);
		ProductDTO productDTO137 = new ProductDTO(137, "Chips", "Doritos", 150d, 30d, 3.8f);
		ProductDTO productDTO138 = new ProductDTO(138, "Chips", "Parle Waters", 100d, 25d, 3.9f);
		ProductDTO productDTO139 = new ProductDTO(139, "Chips", "Tagz", 120d, 35d, 2.8f);
		ProductDTO productDTO140 = new ProductDTO(140, "Chips", "Haldirams", 150d, 35d, 3.2f);
		ProductDTO productDTO141 = new ProductDTO(141, "Chips", "uncle Chipps", 50d, 15d, 3.1f);
		ProductDTO productDTO142 = new ProductDTO(142, "Chips", "Pringles", 500d, 250d, 3.7f);
		ProductDTO productDTO143 = new ProductDTO(143, "Chips", "Walkers", 250d, 160d, 4f);
		ProductDTO productDTO144 = new ProductDTO(144, "Chips", "Doritos", 150d, 70d, 3.9f);
		ProductDTO productDTO145 = new ProductDTO(145, "Salt", "Ghadi", 500d, 28d, 3.5f);
		ProductDTO productDTO146 = new ProductDTO(146, "salt", "Patanjali", 1d, 37d, 3.9f);
		ProductDTO productDTO147 = new ProductDTO(147, "Namak", "Star", 500d, 33d, 3.7f);
		ProductDTO productDTO148 = new ProductDTO(148, "agarbati", "Duph", 200d, 25d, 3.8f);
		ProductDTO productDTO149 = new ProductDTO(149, "Toothpaste", "Babool", 120d, 30d, 4f);
		ProductDTO productDTO150 = new ProductDTO(150, "Toothpaste", "Meswak", 80d, 30d, 4.2f);

		List<ProductDTO> productDTOs = new LinkedList<ProductDTO>();
		productDTOs.add(productDTO);
		productDTOs.add(productDTO1);
		productDTOs.add(productDTO2);
		productDTOs.add(productDTO3);
		productDTOs.add(productDTO4);
		productDTOs.add(productDTO5);
		productDTOs.add(productDTO6);
		productDTOs.add(productDTO7);
		productDTOs.add(productDTO8);
		productDTOs.add(productDTO9);
		productDTOs.add(productDTO10);
		productDTOs.add(productDTO11);
		productDTOs.add(productDTO12);
		productDTOs.add(productDTO13);
		productDTOs.add(productDTO14);
		productDTOs.add(productDTO15);
		productDTOs.add(productDTO16);
		productDTOs.add(productDTO17);
		productDTOs.add(productDTO18);
		productDTOs.add(productDTO19);
		productDTOs.add(productDTO20);
		productDTOs.add(productDTO21);
		productDTOs.add(productDTO22);
		productDTOs.add(productDTO23);
		productDTOs.add(productDTO24);
		productDTOs.add(productDTO25);
		productDTOs.add(productDTO26);
		productDTOs.add(productDTO27);
		productDTOs.add(productDTO28);
		productDTOs.add(productDTO29);
		productDTOs.add(productDTO30);
		productDTOs.add(productDTO31);
		productDTOs.add(productDTO32);
		productDTOs.add(productDTO33);
		productDTOs.add(productDTO34);
		productDTOs.add(productDTO35);
		productDTOs.add(productDTO36);
		productDTOs.add(productDTO37);
		productDTOs.add(productDTO38);
		productDTOs.add(productDTO39);
		productDTOs.add(productDTO40);
		productDTOs.add(productDTO41);
		productDTOs.add(productDTO42);
		productDTOs.add(productDTO43);
		productDTOs.add(productDTO44);
		productDTOs.add(productDTO45);
		productDTOs.add(productDTO46);
		productDTOs.add(productDTO47);
		productDTOs.add(productDTO48);
		productDTOs.add(productDTO49);
		productDTOs.add(productDTO50);
		productDTOs.add(productDTO51);
		productDTOs.add(productDTO52);
		productDTOs.add(productDTO53);
		productDTOs.add(productDTO54);
		productDTOs.add(productDTO55);
		productDTOs.add(productDTO56);
		productDTOs.add(productDTO57);
		productDTOs.add(productDTO58);
		productDTOs.add(productDTO59);
		productDTOs.add(productDTO60);
		productDTOs.add(productDTO61);
		productDTOs.add(productDTO62);
		productDTOs.add(productDTO63);
		productDTOs.add(productDTO64);
		productDTOs.add(productDTO65);
		productDTOs.add(productDTO66);
		productDTOs.add(productDTO67);
		productDTOs.add(productDTO68);
		productDTOs.add(productDTO69);
		productDTOs.add(productDTO70);
		productDTOs.add(productDTO71);
		productDTOs.add(productDTO72);
		productDTOs.add(productDTO73);
		productDTOs.add(productDTO74);
		productDTOs.add(productDTO75);
		productDTOs.add(productDTO76);
		productDTOs.add(productDTO77);
		productDTOs.add(productDTO78);
		productDTOs.add(productDTO79);
		productDTOs.add(productDTO80);
		productDTOs.add(productDTO81);
		productDTOs.add(productDTO82);
		productDTOs.add(productDTO83);
		productDTOs.add(productDTO84);
		productDTOs.add(productDTO85);
		productDTOs.add(productDTO86);
		productDTOs.add(productDTO87);
		productDTOs.add(productDTO88);
		productDTOs.add(productDTO89);
		productDTOs.add(productDTO90);
		productDTOs.add(productDTO91);
		productDTOs.add(productDTO92);
		productDTOs.add(productDTO93);
		productDTOs.add(productDTO94);
		productDTOs.add(productDTO95);
		productDTOs.add(productDTO96);
		productDTOs.add(productDTO97);
		productDTOs.add(productDTO98);
		productDTOs.add(productDTO99);
		productDTOs.add(productDTO100);
		productDTOs.add(productDTO101);
		productDTOs.add(productDTO102);
		productDTOs.add(productDTO103);
		productDTOs.add(productDTO104);
		productDTOs.add(productDTO105);
		productDTOs.add(productDTO106);
		productDTOs.add(productDTO107);
		productDTOs.add(productDTO108);
		productDTOs.add(productDTO109);
		productDTOs.add(productDTO110);
		productDTOs.add(productDTO111);
		productDTOs.add(productDTO112);
		productDTOs.add(productDTO113);
		productDTOs.add(productDTO114);
		productDTOs.add(productDTO115);
		productDTOs.add(productDTO116);
		productDTOs.add(productDTO117);
		productDTOs.add(productDTO118);
		productDTOs.add(productDTO119);
		productDTOs.add(productDTO120);
		productDTOs.add(productDTO121);
		productDTOs.add(productDTO122);
		productDTOs.add(productDTO123);
		productDTOs.add(productDTO124);
		productDTOs.add(productDTO125);
		productDTOs.add(productDTO126);
		productDTOs.add(productDTO127);
		productDTOs.add(productDTO128);
		productDTOs.add(productDTO129);
		productDTOs.add(productDTO130);
		productDTOs.add(productDTO131);
		productDTOs.add(productDTO132);
		productDTOs.add(productDTO133);
		productDTOs.add(productDTO134);
		productDTOs.add(productDTO135);
		productDTOs.add(productDTO136);
		productDTOs.add(productDTO137);
		productDTOs.add(productDTO138);
		productDTOs.add(productDTO139);
		productDTOs.add(productDTO140);
		productDTOs.add(productDTO141);
		productDTOs.add(productDTO142);
		productDTOs.add(productDTO143);
		productDTOs.add(productDTO144);
		productDTOs.add(productDTO145);
		productDTOs.add(productDTO146);
		productDTOs.add(productDTO147);
		productDTOs.add(productDTO148);
		productDTOs.add(productDTO149);
		productDTOs.add(productDTO150);

		System.out.println(productDTO);
		System.out.println(productDTO1);
		System.out.println(productDTO2);
		System.out.println(productDTO3);
		System.out.println(productDTO4);
		System.out.println(productDTO5);
		System.out.println(productDTO6);
		System.out.println(productDTO7);
		System.out.println(productDTO8);
		System.out.println(productDTO9);
		System.out.println(productDTO10);
		System.out.println(productDTO11);
		System.out.println(productDTO12);
		System.out.println(productDTO13);
		System.out.println(productDTO14);
		System.out.println(productDTO15);
		System.out.println(productDTO16);
		System.out.println(productDTO17);
		System.out.println(productDTO18);
		System.out.println(productDTO19);
		System.out.println(productDTO20);
		System.out.println(productDTO21);
		System.out.println(productDTO22);
		System.out.println(productDTO23);
		System.out.println(productDTO24);
		System.out.println(productDTO25);
		System.out.println(productDTO26);
		System.out.println(productDTO27);
		System.out.println(productDTO28);
		System.out.println(productDTO29);
		System.out.println(productDTO30);
		System.out.println(productDTO31);
		System.out.println(productDTO32);
		System.out.println(productDTO33);
		System.out.println(productDTO34);
		System.out.println(productDTO35);
		System.out.println(productDTO36);
		System.out.println(productDTO37);
		System.out.println(productDTO38);
		System.out.println(productDTO39);
		System.out.println(productDTO40);
		System.out.println(productDTO41);
		System.out.println(productDTO42);
		System.out.println(productDTO43);
		System.out.println(productDTO44);
		System.out.println(productDTO45);
		System.out.println(productDTO46);
		System.out.println(productDTO47);
		System.out.println(productDTO48);
		System.out.println(productDTO49);
		System.out.println(productDTO50);
		System.out.println(productDTO51);
		System.out.println(productDTO52);
		System.out.println(productDTO53);
		System.out.println(productDTO54);
		System.out.println(productDTO55);
		System.out.println(productDTO56);
		System.out.println(productDTO57);
		System.out.println(productDTO58);
		System.out.println(productDTO59);
		System.out.println(productDTO60);
		System.out.println(productDTO61);
		System.out.println(productDTO62);
		System.out.println(productDTO63);
		System.out.println(productDTO64);
		System.out.println(productDTO65);
		System.out.println(productDTO66);
		System.out.println(productDTO67);
		System.out.println(productDTO68);
		System.out.println(productDTO69);
		System.out.println(productDTO70);
		System.out.println(productDTO71);
		System.out.println(productDTO72);
		System.out.println(productDTO73);
		System.out.println(productDTO74);
		System.out.println(productDTO75);
		System.out.println(productDTO76);
		System.out.println(productDTO77);
		System.out.println(productDTO78);
		System.out.println(productDTO79);
		System.out.println(productDTO80);
		System.out.println(productDTO81);
		System.out.println(productDTO82);
		System.out.println(productDTO83);
		System.out.println(productDTO84);
		System.out.println(productDTO85);
		System.out.println(productDTO86);
		System.out.println(productDTO87);
		System.out.println(productDTO88);
		System.out.println(productDTO89);
		System.out.println(productDTO90);
		System.out.println(productDTO91);
		System.out.println(productDTO92);
		System.out.println(productDTO93);
		System.out.println(productDTO94);
		System.out.println(productDTO95);
		System.out.println(productDTO96);
		System.out.println(productDTO97);
		System.out.println(productDTO98);
		System.out.println(productDTO99);
		System.out.println(productDTO100);
		System.out.println(productDTO101);
		System.out.println(productDTO102);
		System.out.println(productDTO103);
		System.out.println(productDTO104);
		System.out.println(productDTO105);
		System.out.println(productDTO106);
		System.out.println(productDTO107);
		System.out.println(productDTO108);
		System.out.println(productDTO109);
		System.out.println(productDTO110);
		System.out.println(productDTO111);
		System.out.println(productDTO112);
		System.out.println(productDTO113);
		System.out.println(productDTO114);
		System.out.println(productDTO115);
		System.out.println(productDTO116);
		System.out.println(productDTO117);
		System.out.println(productDTO118);
		System.out.println(productDTO119);
		System.out.println(productDTO120);
		System.out.println(productDTO121);
		System.out.println(productDTO122);
		System.out.println(productDTO123);
		System.out.println(productDTO124);
		System.out.println(productDTO125);
		System.out.println(productDTO126);
		System.out.println(productDTO127);
		System.out.println(productDTO128);
		System.out.println(productDTO129);
		System.out.println(productDTO130);
		System.out.println(productDTO131);
		System.out.println(productDTO132);
		System.out.println(productDTO133);
		System.out.println(productDTO134);
		System.out.println(productDTO135);
		System.out.println(productDTO136);
		System.out.println(productDTO137);
		System.out.println(productDTO138);
		System.out.println(productDTO139);
		System.out.println(productDTO140);
		System.out.println(productDTO141);
		System.out.println(productDTO142);
		System.out.println(productDTO143);
		System.out.println(productDTO144);
		System.out.println(productDTO145);
		System.out.println(productDTO146);
		System.out.println(productDTO147);
		System.out.println(productDTO148);
		System.out.println(productDTO149);
		System.out.println(productDTO150);

		System.err.println("******************************************");
		
		Comparator<ProductDTO> comparator = new ProductAscId();
		System.err.println("*******************01***********************");

		Collections.sort(productDTOs, comparator);
		for (ProductDTO productDTOss : productDTOs) {
			System.out.println( productDTOss);
		}
		Comparator<ProductDTO> comparator1 = new ProductDescId();
		System.err.println("*******************02***********************");
		Collections.sort(productDTOs, comparator1);
		for (ProductDTO  productDTOss: productDTOs) {
			System.out.println( productDTOss);
		}
 
		Comparator<ProductDTO> comparator2 = new ProductAscName();
		System.err.println("*******************03***********************");

		Collections.sort(productDTOs, comparator2);
		for (ProductDTO  productDTOss : productDTOs) {
			System.out.println( productDTOss);
		}

		Comparator<ProductDTO> comparator3 = new ProductDescName();
		System.err.println("*******************04***********************");
		Collections.sort(productDTOs, comparator3);
		for (ProductDTO  productDTOss : productDTOs) {
			System.out.println( productDTOss);
		}
		
		Comparator<ProductDTO> comparator4 = new ProductAscCompany();
		System.err.println("*******************05***********************");
		Collections.sort(productDTOs, comparator4);
		for (ProductDTO  productDTOss : productDTOs) {
			System.out.println( productDTOss);
		}
		Comparator<ProductDTO> comparator5 = new ProductDescCompany();
		System.err.println("*******************06***********************");
		Collections.sort(productDTOs, comparator5);
		for (ProductDTO  productDTOss : productDTOs) {
			System.out.println( productDTOss);
		}
		
		Comparator<ProductDTO> comparator6 = new ProductAscQuality();
		System.err.println("*******************07***********************");

		Collections.sort(productDTOs, comparator6);
		for (ProductDTO  productDTOss : productDTOs) {
			System.out.println( productDTOss);
		}
		Comparator<ProductDTO> comparator7 = new ProductDescQuality();
		System.err.println("*******************08***********************");
		Collections.sort(productDTOs, comparator7);
		for (ProductDTO  productDTOss : productDTOs) {
			System.out.println( productDTOss);
		}
		
		Comparator<ProductDTO> comparator8 = new ProductAscPrice();
		System.err.println("*******************09***********************");
		Collections.sort(productDTOs, comparator8);
		for (ProductDTO  productDTOss : productDTOs) {
			System.out.println( productDTOss);
		}
	
		Comparator<ProductDTO> comparator9 = new ProductDescPrice();
		System.err.println("*******************10***********************");
		Collections.sort(productDTOs, comparator9);
		for (ProductDTO  productDTOss : productDTOs) {
			System.out.println( productDTOss);
		}
		
		Comparator<ProductDTO> comparator10 = new ProductAscQuantity();
		System.err.println("*******************11***********************");
		Collections.sort(productDTOs, comparator10);
		for (ProductDTO  productDTOss : productDTOs) {
			System.out.println( productDTOss);
		}
		
		Comparator<ProductDTO> comparator11 = new ProductDescQuantity();
		System.err.println("*****************12*************************");
		Collections.sort(productDTOs, comparator11);
		for (ProductDTO  productDTOss: productDTOs) {
			System.out.println( productDTOss);
		}
		
		}
	}

