package com.xworkz.collection;

import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collectors;

public class CountryName {

	public static void main(String[] args) {

		List<String> countryName = new LinkedList<String>();
		countryName.add("Albania");
		countryName.add("Algeria");
		countryName.add("Angola");
		countryName.add("Antigua and Barbuda");
		countryName.add("Argentina");
		countryName.add("Armenia");
		countryName.add("Australia");
		countryName.add("Austria");
		countryName.add("Azerbaijan");
		countryName.add("Bahamas");
		countryName.add("Bahrain");
		countryName.add("Bangladesh");
		countryName.add("Barbados");
		countryName.add("Belarus");
		countryName.add("Belgium");
		countryName.add("Belize");
		countryName.add("Benin	");
		countryName.add("Bhutan");
		countryName.add("Bolivia");
		countryName.add("Bosnia and Herzegovina");
		countryName.add("Botswana");
		countryName.add("Brazil");
		countryName.add("Brunei");
		countryName.add("Bulgaria");
		countryName.add("Burkina Faso");
		countryName.add("Burundi");
		countryName.add("Côte d'Ivoire");
		countryName.add("Cabo Verde");
		countryName.add("Cambodia");
		countryName.add("Cameroon");
		countryName.add("Canada");
		countryName.add("Central");
		countryName.add("Chad");
		countryName.add("Chile");
		countryName.add("China");
		countryName.add("Colombia");
		countryName.add("Comoros");
		countryName.add("Congo");
		countryName.add("Costa Rica");
		countryName.add("Croatia");
		countryName.add("Cuba");
		countryName.add("Cyprus");
		countryName.add("Czechia");
		countryName.add("Democratic Republic of the Congo");
		countryName.add("Denmark");
		countryName.add("Djibouti");
		countryName.add("Dominica");
		countryName.add("Dominican Republic");
		countryName.add("Ecuador");
		countryName.add("Egypt");
		countryName.add("El Salvador");
		countryName.add("Equatorial Guinea");
		countryName.add("Eritrea");
		countryName.add("Estonia");
		countryName.add("Eswatini");
		countryName.add("Ethiopia");
		countryName.add("Fiji");
		countryName.add("Finland");
		countryName.add("France");
		countryName.add("Gabon");
		countryName.add("Gambia");
		countryName.add("Georgia");
		countryName.add("Germany");
		countryName.add("Ghana");
		countryName.add("Greece");
		countryName.add("Grenada");
		countryName.add("Guatemala");
		countryName.add("Guinea");
		countryName.add("Guinea-Bissau");
		countryName.add("Guyana");
		countryName.add("Haiti");
		countryName.add("Holy See");
		countryName.add("Honduras");
		countryName.add("Hungary");
		countryName.add("Iceland");
		countryName.add("India");
		countryName.add("Indonesia");
		countryName.add("Iran");
		countryName.add("Iraq");
		countryName.add("Ireland");
		countryName.add("Israel");
		countryName.add("Italy");
		countryName.add("Jamaica");
		countryName.add("Japan");
		countryName.add("Jordan");
		countryName.add("Kazakhstan");
		countryName.add("Kenya	");
		countryName.add("Kiribati");
		countryName.add("Kuwait");
		countryName.add("Kyrgyzstan");
		countryName.add("Laos");
		countryName.add("Latvia");
		countryName.add("Lebanon");
		countryName.add("Lesotho");
		countryName.add("Liberia");
		countryName.add("Libya");
		countryName.add("Liechtenstein");
		countryName.add("Lithuania");
		countryName.add("Luxembourg");
		countryName.add("Madagascar");
		countryName.add("Malawi");
		countryName.add("Malaysia");
		countryName.add("Maldives");
		countryName.add("Mali");
		countryName.add("Malta");
		countryName.add("Marshall Islands");
		countryName.add("Mauritania");
		countryName.add("Mauritius");
		countryName.add("Mexico");
		countryName.add("Micronesia");
		countryName.add("Moldova");
		countryName.add("Monaco");
		countryName.add("Mongolia");
		countryName.add("Montenegro");
		countryName.add("Morocco");
		countryName.add("Mozambique");
		countryName.add("Myanmar");
		countryName.add("Namibia");
		countryName.add("Nauru");
		countryName.add("Nepal");
		countryName.add("Netherlands");
		countryName.add("New Zealand");
		countryName.add("Nicaragua");
		countryName.add("Niger");
		countryName.add("Nigeria");
		countryName.add("North Korea");
		countryName.add("North Macedonia");
		countryName.add("Norway");
		countryName.add("Oman");
		countryName.add("Pakistan");
		countryName.add("Palau");
		countryName.add("Palestine State");
		countryName.add("Panama");
		countryName.add("Papua New Guinea");
		countryName.add("Paraguay");
		countryName.add("Peru");
		countryName.add("Philippines");
		countryName.add("Poland");
		countryName.add("Portugal");
		countryName.add("Qatar");
		countryName.add("Romania");
		countryName.add("Russia");
		countryName.add("Rwanda");
		countryName.add("Saint Kitts and Nevis");
		countryName.add("Saint Lucia");
		countryName.add("Saint Vincent and the Grenadines");
		countryName.add("Samoa");
		countryName.add("San Marino");
		countryName.add("Sao Tome and Principe");
		countryName.add("Saudi Arabia");
		countryName.add("Senegal");
		countryName.add("Serbia");
		countryName.add("Seychelles");
		countryName.add("Sierra Leone");
		countryName.add("Singapore");
		countryName.add("Slovakia");
		countryName.add("Slovenia");
		countryName.add("Solomon Islands");
		countryName.add("Somalia");
		countryName.add("South Africa");
		countryName.add("South Korea");
		countryName.add("South Sudan");
		countryName.add("Spain");
		countryName.add("Sri Lanka");
		countryName.add("Sudan");
		countryName.add("Suriname");
		countryName.add("Sweden");
		countryName.add("Switzerland");
		countryName.add("Syria");
		countryName.add("Tajikistan");
		countryName.add("Tanzania");
		countryName.add("Thailand");
		countryName.add("Timor-Leste");
		countryName.add("Togo");
		countryName.add("Tonga");
		countryName.add("Trinidad and Tobago");
		countryName.add("Tunisia");
		countryName.add("Turkey");
		countryName.add("Turkmenistan");
		countryName.add("Tuvalu");
		countryName.add("Uganda");
		countryName.add("Ukraine");
		countryName.add("United Arab Emirates");
		countryName.add("United Kingdom");
		countryName.add("United States of America");
		countryName.add("Uruguay");
		countryName.add("Uzbekistan");
		countryName.add("Vanuatu");
		countryName.add("Venezuela");
		countryName.add("Vietnam");
		countryName.add("Yemen");
		countryName.add("Zambia");
		countryName.add("Zimbabwe");

		Comparator<String> desc = (obj1, obj2) -> {
			return obj2.compareTo(obj1);
		};
		Collections.sort(countryName, desc);
		System.err.println("Country Name in Desc order");

		Predicate<String> predicate = (string) -> {
			return string.endsWith("a");
		};
		List<String> temp = countryName.stream().filter(predicate).collect(Collectors.toList());
		for (String string1 : temp) {
			System.out.println(string1);
		}
		;

	}
}
