package com.xworkz.collection;

import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;

public class PadmashriAwardees {

	public static void main(String[] args) {

		List<String> padmashri = new LinkedList<String>();
		padmashri.add("Gulfam Ahmed");
		padmashri.add("P. Anitha ");
		padmashri.add("Rama Swamy Annavarapu");
		padmashri.add("Dr. Yogi Aeron");
		padmashri.add("Shri Jai Prakash Agarwal");
		padmashri.add("Guru Shashadhar Acharya");
		padmashri.add("Kazi Masum Akhtar");
		padmashri.add("Ms. Gloria Arieira");
		padmashri.add("Khan Zaheerkhan Bakhtiyarkhan");
		padmashri.add("Dr. Padmavathy Bandopadhyay");
		padmashri.add("Dr. Sushovan Banerjee");
		padmashri.add("Dr. Digambar Behera");
		padmashri.add("Dr. Damayanti Beshra");
		padmashri.add("Shri Pawar Popatrao Bhaguji");
		padmashri.add("Shri Himmata Ram Bhambhu");
		padmashri.add("Shri Sanjeev Bikhchandani");
		padmashri.add("Shri Gafurbhai M. Bilakhia");
		padmashri.add("Shri Bob Blackman");
		padmashri.add("Ms. Indira P. P. Bora");
		padmashri.add("Shri Madan Singh Chauhan");
		padmashri.add("Ms. Usha Chaumar");
		padmashri.add("Shri Lil Bahadur Chettri");
		padmashri.add("Ms. Lalitha & Ms. Saroja");
		padmashri.add("Dr. Vajira Chitrasena");
		padmashri.add("Dr. Purushottam Dadheech");
		padmashri.add("Shri Utsav Charan Das");
		padmashri.add("Prof. Indra Dassanayake");
		padmashri.add("Shri H. M. Desai");
		padmashri.add("Shri Manohar Devadoss");
		padmashri.add("Ms. Oinam Bembem Devi");
		padmashri.add("Ms. Lia Diskin");
		padmashri.add("Shri M. P. Ganesh");
		padmashri.add("Dr. Bangalore Gangadhar");
		padmashri.add("Dr. Raman Gangakhedkar");
		padmashri.add("Shri Barry Gardiner");
		padmashri.add("Shri Chewang Motup Goba");
		padmashri.add("Shri Bharat Goenka");
		padmashri.add("Shri Yadla Gopalarao");
		padmashri.add("Shri Mitrabhanu Gountia");
		padmashri.add("Ms. Tulasi Gowda");
		padmashri.add("Shri Sujoy K. Guha");
		padmashri.add("Shri Harekala Hajabba");
		padmashri.add("Shri Enamul Haque");
		padmashri.add("Shri Madhu Mansuri Hasmukh");
		padmashri.add("Abdul Jabbar");
		padmashri.add("Bimal Kumar Jain");
		padmashri.add("Ms. Meenakshi Jain");
		padmashri.add("Nemnath Jain");
		padmashri.add("Ms. Shanti Jain");
		padmashri.add("Karan Johar");
		padmashri.add("Dr. Leela Joshi");
		padmashri.add("Ms. Sarita Joshi");
		padmashri.add("C. Kamlova");
		padmashri.add("Dr. Ravi Kannan R.");
		padmashri.add("Ms. Ekta Kapoor");
		padmashri.add("V. K. Munusamy");
		padmashri.add("Shri M. K. Kunjol");
		padmashri.add("Dr. Narindar Nath Khanna");
		padmashri.add("Naveen Khanna");
		padmashri.add("M. K. Kunjol");
		padmashri.add("Manmohan Maapatra");
		padmashri.add("Ustad Anwar Khan Mangniyar");
		padmashri.add("Kattungal Subramaniam");
		padmashri.add("Munna Master");
		padmashri.add("Prof. Abhiraj Rajendra Mishra");
		padmashri.add("Binapani Mohanty");
		padmashri.add("Dr. Arunoday Mondal");
		padmashri.add("Dr. Prithwindra Mukherjee");
		padmashri.add("Sathyanarayan Mundayoo");
		padmashri.add("Manilal Nag.");
		padmashri.add("N. Chandrasekharan Nair");
		padmashri.add("Dr. Tetsu Nakamura");
		padmashri.add("Shiv Datt Nirmohi");
		padmashri.add("Pu Lalbiakthanga Pachuau");
		padmashri.add("Moozhikkal Pankajakshi");
		padmashri.add("Prasanta Kumar Pattanaik");
		padmashri.add("Jogendra Nath Phukan");
		padmashri.add("Rahibai Soma Popere");
		padmashri.add("Yogesh Praveen");
		padmashri.add("Jitu Rai");
		padmashri.add("Tarundeep Rai");
		padmashri.add("S.Ramakrishnan");
		padmashri.add("Rani Rampal");
		padmashri.add("Kangana Ranaut");
		padmashri.add("Dalavai Chalapathi Rao");
		padmashri.add("Shahbuddin Rathod");
		padmashri.add("Kalyan Singh Rawat");
		padmashri.add("Chintala Venkat Reddy");
		padmashri.add("Smt. (Dr.) Shanti Roy");
		padmashri.add("Radhammohan");
		padmashri.add("Batakrushna Sahoo");
		padmashri.add("Trinity Saioo");
		padmashri.add("Adnan Sami");
		padmashri.add("Vijay Sankeshwar");
		padmashri.add("Dr. Kushal Konwar Sarma");
		padmashri.add("Sayed Mehboob Shah Qadri");
		padmashri.add("Mohammed Sharif");
		padmashri.add("Shyam Sunder Sharma");
		padmashri.add("Dr. Gurdip Singh");
		padmashri.add("Ramjee Singh");
		padmashri.add("Gulfam Ahmed");
		padmashri.add("P. Anitha ");
		padmashri.add("Rama Swamy Annavarapu");
		padmashri.add("Dr. Yogi Aeron");
		padmashri.add("Shri Jai Prakash Agarwal");
		padmashri.add("Guru Shashadhar Acharya");
		padmashri.add("Kazi Masum Akhtar");
		padmashri.add("Ms. Gloria Arieira");
		padmashri.add("Khan Zaheerkhan Bakhtiyarkhan");
		padmashri.add("Dr. Padmavathy Bandopadhyay");
		padmashri.add("Dr. Sushovan Banerjee");
		padmashri.add("Dr. Digambar Behera");
		padmashri.add("Dr. Damayanti Beshra");
		padmashri.add("Shri Pawar Popatrao Bhaguji");
		padmashri.add("Shri Himmata Ram Bhambhu");
		padmashri.add("Shri Sanjeev Bikhchandani");
		padmashri.add("Shri Gafurbhai M. Bilakhia");
		padmashri.add("Shri Bob Blackman");
		padmashri.add("Ms. Indira P. P. Bora");
		padmashri.add("Shri Madan Singh Chauhan");
		padmashri.add("Ms. Usha Chaumar");
		padmashri.add("Shri Lil Bahadur Chettri");
		padmashri.add("Ms. Lalitha & Ms. Saroja");
		padmashri.add("Dr. Vajira Chitrasena");
		padmashri.add("Dr. Purushottam Dadheech");
		padmashri.add("Shri Utsav Charan Das");
		padmashri.add("Prof. Indra Dassanayake");
		padmashri.add("Shri H. M. Desai");
		padmashri.add("Shri Manohar Devadoss");
		padmashri.add("Ms. Oinam Bembem Devi");
		padmashri.add("Ms. Lia Diskin");
		padmashri.add("Shri M. P. Ganesh");
		padmashri.add("Dr. Bangalore Gangadhar");
		padmashri.add("Dr. Raman Gangakhedkar");
		padmashri.add("Shri Barry Gardiner");
		padmashri.add("Shri Chewang Motup Goba");
		padmashri.add("Shri Bharat Goenka");
		padmashri.add("Shri Yadla Gopalarao");
		padmashri.add("Shri Mitrabhanu Gountia");
		padmashri.add("Ms. Tulasi Gowda");
		padmashri.add("Shri Sujoy K. Guha");
		padmashri.add("Shri Harekala Hajabba");
		padmashri.add("Shri Enamul Haque");
		padmashri.add("Shri Madhu Mansuri Hasmukh");
		padmashri.add("Abdul Jabbar");
		padmashri.add("Bimal Kumar Jain");
		padmashri.add("Ms. Meenakshi Jain");
		padmashri.add("Nemnath Jain");
		padmashri.add("Ms. Shanti Jain");
		padmashri.add("Karan Johar");
		padmashri.add("Dr. Leela Joshi");
		padmashri.add("Ms. Sarita Joshi");
		padmashri.add("C. Kamlova");
		padmashri.add("Dr. Ravi Kannan R.");
		padmashri.add("Ms. Ekta Kapoor");
		padmashri.add("V. K. Munusamy");
		padmashri.add("Shri M. K. Kunjol");
		padmashri.add("Dr. Narindar Nath Khanna");
		padmashri.add("Naveen Khanna");
		padmashri.add("M. K. Kunjol");
		padmashri.add("Manmohan Maapatra");
		padmashri.add("Ustad Anwar Khan Mangniyar");
		padmashri.add("Kattungal Subramaniam");
		padmashri.add("Munna Master");
		padmashri.add("Prof. Abhiraj Rajendra Mishra");
		padmashri.add("Binapani Mohanty");
		padmashri.add("Dr. Arunoday Mondal");
		padmashri.add("Dr. Prithwindra Mukherjee");
		padmashri.add("Sathyanarayan Mundayoo");
		padmashri.add("Manilal Nag.");
		padmashri.add("N. Chandrasekharan Nair");
		padmashri.add("Dr. Tetsu Nakamura");
		padmashri.add("Shiv Datt Nirmohi");
		padmashri.add("Pu Lalbiakthanga Pachuau");
		padmashri.add("Moozhikkal Pankajakshi");
		padmashri.add("Prasanta Kumar Pattanaik");
		padmashri.add("Jogendra Nath Phukan");
		padmashri.add("Rahibai Soma Popere");
		padmashri.add("Yogesh Praveen");
		padmashri.add("Jitu Rai");
		padmashri.add("Tarundeep Rai");
		padmashri.add("S.Ramakrishnan");
		padmashri.add("Rani Rampal");
		padmashri.add("Kangana Ranaut");
		padmashri.add("Dalavai Chalapathi Rao");
		padmashri.add("Shahbuddin Rathod");
		padmashri.add("Kalyan Singh Rawat");
		padmashri.add("Chintala Venkat Reddy");
		padmashri.add("Smt. (Dr.) Shanti Roy");
		padmashri.add("Radhammohan");
		padmashri.add("Batakrushna Sahoo");
		padmashri.add("Trinity Saioo");
		padmashri.add("Adnan Sami");
		padmashri.add("Vijay Sankeshwar");
		padmashri.add("Dr. Kushal Konwar Sarma");
		padmashri.add("Sayed Mehboob Shah Qadri");
		padmashri.add("Mohammed Sharif");
		padmashri.add("Shyam Sunder Sharma");
		padmashri.add("Dr. Gurdip Singh");
		padmashri.add("Ramjee Singh");
		padmashri.add("Vashishtha Narayan Singh");
		padmashri.add("Daya Prakash Sinha");
		padmashri.add("Dr. Sandra Desa Souza");
		padmashri.add("Vijayasarathi Sribhashyam");
		padmashri.add("Javed Ahmad Tak");
		padmashri.add("Pradeep Thalappil");
		padmashri.add("Yeshe Dorjee Thongchi");
		padmashri.add("Robert Thurman");
		padmashri.add("Agus Indra Udayana");
		padmashri.add("Harish Chandra Verma");
		padmashri.add("Sundaram Verma");
		padmashri.add("Dr. Romesh Tekchand");
		padmashri.add("Prem Watsa");
		padmashri.add("Suresh Wadakar");

		Comparator<String> desc = (P1, P2) -> {
			return P2.compareTo(P1);
		};

		Collections.sort(padmashri, desc);
		System.err.println("PadmashriAwardees Name in Desc order");

		for (String yeppa : padmashri) {
			System.out.println(yeppa);
		};

	}

}
